FROM --platform=$BUILDPLATFORM ubuntu:noble AS build-env

# Set environment variable
ENV APP_NAME=cf-ddns
ENV HOME=/root
ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn
ENV GOOS=linux
ENV GOARCH=arm64
ENV CGO_ENABLED=1
ENV CC=aarch64-linux-gnu-gcc
ENV CXX=aarch64-linux-gnu-g++
ENV GOROOT=/usr/local/go
ENV GOPATH=$HOME/go
ENV PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# install crossbuilding gcc and g++
RUN apt update && \
    apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu curl

RUN curl -L https://go.dev/dl/go1.23.0.linux-amd64.tar.gz | tar -C /usr/local -xz

RUN go version

# Copy application data into image
COPY . $GOPATH/src/$APP_NAME
WORKDIR $GOPATH/src/$APP_NAME

RUN go build -v -o /$APP_NAME $GOPATH/src/$APP_NAME/

FROM ubuntu:noble AS run-env

# Set environment variable
ENV APP_NAME=cf-ddns

# Copy only required data into this image
COPY --from=build-env /$APP_NAME .

# Start app
CMD ./$APP_NAME
